Disable the use of session tickets on TLSv1.2 by default
urllib3/urllib3 pull request #1970
Opened 2020-09-18 22:17 UTC by PleasantMachine9

See #1886  and #1898 

> Since currently session resumption is not supported by urllib3,
> there is no reason to request tickets from the server.
> It takes up extra bytes in transit (~200 bytes), and raises
> some minor security concerns.
> 
> See also: https://blog.filippo.io/we-need-to-talk-about-session-tickets/

Hopefully we can add support for resumption, but until then, this flag (NO_TICKET) has no reason to be off.

2020-09-18 22:26 UTC, PleasantMachine9 commented
> test_ssl_failed_fingerprint_verification 
> where MaxRetryError("HTTPSConnectionPool(host='localhost', port=49868): Max retries exceeded with url: / (Caused by NewConne...ection.HTTPSConnection object at 0x10c3e5190>: Failed to establish a new connection: [Errno 61] Connection refused'))") = <ExceptionInfo MaxRetryError tblen=4>.value

This looks like a flaky test case to me? I don't see how my change would affect this TC.

2020-09-18 23:23 UTC, sethmlarson commented
> This looks like a flaky test case to me? I don't see how my change would affect this TC.

Our CI is a bit flaky sometimes :) might not have been caused by your change.

2020-09-18 23:27 UTC, sethmlarson requested changes
It may not say so in the Python documentation, but according to OpenSSL `OP_NO_TICKET` is meant for servers only?

https://www.openssl.org/docs/man1.1.1/man3/SSL_set_options.html

2020-09-18 23:36 UTC, sethmlarson commented
So I confirmed in Wireshark that for TLS 1.2 specifically setting `OP_NO_TICKET` does indeed disable the `session_ticket (35)` extension from being sent with ClientHello.

2020-09-18 23:42 UTC, PleasantMachine9 commented
Practically speaking it wouldn't make sense for it to be server-side only, so it's probably a documentation issue in openssl.

As per the RFC detailing tickets for TLS 1.2, the _client_ is the first party to indicate whether they support tickets, by including the empty extension.

So it makes sense that we should be able to tell openssl not to send that extension.

2020-09-18 23:51 UTC, PleasantMachine9 commented
Trying again for the TCs

2020-09-25 02:38 UTC, sethmlarson approved these changes
This looks good to me now, thanks for putting this together!

2020-09-25 17:25 UTC, merged