extend LifoQueue from python
urllib3/urllib3 pull request #2181
Opened 2021-03-15 12:34 UTC by dulmandakh

This PR changes LifoQueue to extend from [queue.LifoQueue](https://github.com/python/cpython/blob/35d5068928ab5485e5f28b60b1e33062bc2c46cc/Lib/queue.py#L242), which uses list as queue internally. LifoQueue was introduced in 2.7 with https://github.com/python/cpython/commit/35641461db7c692877ffa4bbbfe31a525c81770e.

2021-03-16 13:31 UTC, pquentin approved these changes
Thanks!

2021-03-16 13:45 UTC, pquentin requested changes
However, now that I think about it more, we don't need a `deque` for a LIFOQueue, and can remove this file to just use `LifoQueue` from Python directly

2021-03-18 17:50 UTC, sethmlarson commented
Made some changes myself, let me know what you think @pquentin

2021-03-18 17:53 UTC, pquentin approved these changes
Thanks!

2021-03-18 17:54 UTC, merged

2021-03-18 17:54 UTC, sethmlarson commented
Thanks to @dulmandakh for making us aware of this improvement :bow: