Added HTTPHeaderDict to top level objects and updated the docs with i…
urllib3/urllib3 pull request #2216
Opened 2021-05-12 15:21 UTC by ubdussamad

I added the HTTPHeaderDict as to the top level objects (`__init.py__`) of urllib3.
I modified the Documentation (`user-guide.rst`) depecting the usecase of HTTPHeaderDict.

This modification solves: Issue #2158

2021-05-12 18:46 UTC, pquentin requested changes
Great start, thanks!

2021-05-12 18:46 UTC, pquentin commented on docs/user-guide.rst
> +    Y-Something: value
You don't need those lines as we're already printing that below anyway

2021-05-12 18:46 UTC, pquentin commented on docs/user-guide.rst
> +    >>> Headers.add('Y-Something', 'value')
Let's use a multi-value HTTP header here, for example Accept with both application/json and text/plain

2021-05-12 18:46 UTC, pquentin commented on docs/user-guide.rst
> +Or you can use the ``HTTPHeaderDict`` class to create a proper variable for storing header information.
```suggestion
Or you can use the ``HTTPHeaderDict`` class to create multi-valued HTTP headers.
```

2021-05-12 18:46 UTC, pquentin commented on docs/user-guide.rst
> +
Any reason to add this blank line? If not let's remove it

2021-05-13 04:07 UTC, ubdussamad reviewed
Pushed the changes according to the suggestions, it's on @pquentin to review and make edit (if need be) whenever he gets the time.

2021-05-17 05:37 UTC, ubdussamad reviewed
Looks good. Let's go ahead.

2021-05-17 07:38 UTC, pquentin approved these changes
Looks good to me, thanks!

2021-05-17 07:51 UTC, pquentin commented
(Let's make sure to squash when merging this.)

2021-05-17 13:16 UTC, sethmlarson approved these changes
This looks great, thanks @ubdussamad and @pquentin!

2021-05-17 13:16 UTC, merged