Add type hints to urllib3.contrib.ntlmpool
urllib3/urllib3 pull request #2261
Opened 2021-06-11 14:36 UTC by hramezani

2021-06-11 14:37 UTC, hramezani commented on src/urllib3/contrib/ntlmpool.py
> +        res.fp = None  # type: ignore
ignore because `error: "HTTPResponse" has no attribute "fp"`

2021-06-11 14:37 UTC, hramezani commented on src/urllib3/contrib/ntlmpool.py
> +        res.fp = None  # type: ignore
ignore because `error: "HTTPResponse" has no attribute "fp"`

2021-06-18 11:57 UTC, sethmlarson requested changes
Nice, few thoughts:

2021-06-18 11:57 UTC, sethmlarson commented on src/urllib3/contrib/ntlmpool.py
> +        headers: Optional[Dict[str, str]] = None,
Mappin[str, str]?

2021-06-18 11:57 UTC, sethmlarson commented on src/urllib3/contrib/ntlmpool.py
> +        retries: int = 3,
Should this be Union[Retry, bool, int] like elsewhere?

2021-06-18 18:45 UTC, sethmlarson reviewed
Missed one thing then we're ready to merge

2021-06-18 18:45 UTC, sethmlarson commented on src/urllib3/contrib/ntlmpool.py
> +from urllib3.response import BaseHTTPResponse
This should be a relative import

2021-06-18 20:19 UTC, hramezani commented on src/urllib3/contrib/ntlmpool.py
> +from urllib3.response import BaseHTTPResponse
Done!

2021-06-19 14:45 UTC, sethmlarson approved these changes
LGTM

2021-06-19 14:46 UTC, merged