Include py.typed file in package to comply with PEP 561
urllib3/urllib3 pull request #2296
Opened 2021-06-22 00:01 UTC by johnthagen

See https://www.python.org/dev/peps/pep-0561/

`mypy` and other type checkers use the presence of a `py.typed` file in the root of the package to signal that the package has inline type annotations to be used for type checking. Including this file allows users of this library to properly type check their usage of this package.

2021-06-22 03:33 UTC, sethmlarson requested changes
Thanks for this! Can we create an integration test that ensures that `mypy` can recognize our types? Basically I'm worried that somehow `py.typed` wouldn't be included in the dists.

Could be something simple like:

- A file that has `import urllib3; urllib3.request("GET", "https://example.com")`
- A file (`ci/downstream/mypy.sh`) that installs `mypy`, `python -m pip install .`, and then runs `mypy` on the Python file above.

What do you think?

2021-06-22 11:20 UTC, johnthagen commented
If we do this, we'll want to test both the `.tar.gz` sdist and the `.whl` wheel, since both use slightly different mechanisms to include package data.

I've never seen another project add this kind of test before, but I can see that it could have some utility. The test would probably need to add a _failing_ type hint and check that `mypy` failed, since I believe if `py.typed` wasn't there, `mypy` would skip over `urllib3` entirely and things would "pass". 

So something like

```py
import urllib3; urllib3.request(0.0, False)
```

2021-06-23 17:11 UTC, sethmlarson commented
@johnthagen If you use `mypy --strict` Mypy will complain about not having types for an import iirc?

2021-06-23 17:59 UTC, johnthagen commented
@sethmlarson Yes, though you can selectively disable any of the `strict` settings.

What I normally do for my projects is to configure `mypy` like this:

```toml
[tool.mypy]
ignore_missing_imports = true
strict = true
```

An example can be viewed here: https://github.com/johnthagen/python-blueprint/blob/master/pyproject.toml#L5

2021-06-23 19:17 UTC, johnthagen commented
Yes, `mypy --strict` could be a way to validate that `urllib3` has the correct types exposed.

2021-07-03 16:56 UTC, sethmlarson approved these changes
LGTM, thank you!

2021-07-03 16:57 UTC, merged