Moved the metadata into setup.cfg
urllib3/urllib3 pull request #2299
Opened 2021-06-23 09:45 UTC by KOLANICH

Added pyproject.toml
Used a well-known external dependency already used by multiple projects to extract version.
`setup.py` is kept for now, but unneeded and can be removed in later commits.

2021-06-23 11:39 UTC, pquentin commented
Thank you for your contribution! So we all would like to use the new and shiny packaging features, but we need to tread carefully to make sure we still support old Python and pip versions and that installation does not get slower.

For example, we made sure to fail gracefully if anyone tried to install urllib3 2.0 using Python 2.7, and you removed that code.

* I guess the first thing here to do is to establish what is the oldest pip/setuptools versions we support. Then we'll see what we can do.
* It's unclear to me when exactly we're going to fetch read_version, but we don't want to install any dependency at run time our install time.

2021-06-23 16:02 UTC, sethmlarson requested changes
Thanks for opening this. It's always unfortunate having to "thumbs-down" a first contribution but I'm not aware of a way to move this change forward.

The error for Python 2.7 and urllib3 v2.0 isn't implementable without `setup.py` and we definitely want that error. If you and @pquentin agree I think we should close this PR.

Perhaps in the future though we can upgrade our packaging config once we're fairly confident we've swayed people using old tooling+Python versions to pin their version to `urllib3<2`?

Thanks again, I hope this won't discourage future contributions to urllib3, we always appreciate them from our community. :heart:

2021-06-23 18:05 UTC, KOLANICH commented
>The error for Python 2.7  isn't implementable without setup.py

Building a wheel (calling `setup.py`) should be decoupled from installing a wheel (calling `pip install --upgrade urllib.whl`). It is not quite correct to not to allow to build wheels on versions that don't support running them, and it is not quite correct not to allow running wheels on the versions they cannot be built on. These are different versions. Checking that a package can be run on the current version is done by pip. Checking that a package can be built on a version is just unneeded, one just builds and if it builds, it is OK. So the check is unneeded.

Also we haven't removed `setup.py` yet.

>and urllib3 v2.0

I don't understand what yoummean.

2021-06-23 18:27 UTC, sethmlarson commented
> It is not quite correct to not to allow to build wheels on versions that don't support running them, and it is not quite correct not to allow running wheels on the versions they cannot be built on. These are different versions.

> Checking that a package can be run on the current version is done by pip.

You'd be surprised how many people run super ancient versions of `pip` (knowingly or not).

Running the following query for yesterday's downloads...

```
SELECT details.installer.version, COUNT(*) AS c
FROM `the-psf.pypi.file_downloads`
WHERE (
  DATE(timestamp) = "2021-06-22"
  AND file.project = 'urllib3'
  AND details.installer.name = 'pip'
) GROUP BY details.installer.version
ORDER BY c DESC
```

pip version | count
-- | --
21.1.2 | 1779466
9.0.3 | 723906
21.0.1 | 376439
19.3.1 | 308286
20.1.1 | 290001
9.0.1 | 244688
20.0.2 | 236729
20.2.2 | 220853
20.3.4 | 173425
20.1 | 173018
18.1 | 172428
19.0.3 | 141841
21.1.1 | 139982
20.2.4 | 127098
20.2.3 | 123579
8.1.1 | 78091
6.1.1 | 75527
20.3.3 | 72689
19.1.1 | 69723
19.2.3 | 44421
20.3.1 | 43908
10.0.1 | 23456
8.1.2 | 16553
21.1 | 13917
20.2.1 | 12363
20.2 | 10899
18.0 | 10764
19.3 | 8943
21.0 | 8293
19.0.2 | 7880
19.2.1 | 7686
19.1 | 6424
1.5.4 | 6205
7.1.2 | 3441
19.0.1 | 3393
20.3 | 2994
7.1.0 | 2993
19.2.2 | 2172
20.0.dev0 | 1980
9.0.2 | 1294
1.5.6 | 1277
10.0.0 | 1218
19.0 | 1206
20.0.1 | 1185
21.0.dev0 | 853
9.0.0 | 637
20.3b1 | 544
19.2 | 422
20.3.2 | 182
6.0.8 | 175
20.2b1 | 174
10.0.0b2 | 54
8.0.2 | 23
7.0.1 | 22
6.0 | 7
21.1.dev0 | 3
20.0 | 2
20.1b1 | 2
7.0.3 | 2
6.0.6 | 2
1.5.5 | 2
7.1.1 | 1

- Total downloads: 5,563,422
- pip<9 downloads: 184,321 (3.31%)

So 3.3% of our installs come from pip versions that don't understand metadata to specify supported Python versions. We want those users to have a better experience than a `SyntaxError` on importing `urllib3` once we release breaking changes dropping support for Python <3.5.

> > and urllib3 v2.0
> 
> I don't understand what you mean.

You can read more here: https://urllib3.readthedocs.io/en/latest/v2-roadmap.html

2021-06-26 10:46 UTC, venthur commented
I'd also argue that putting almost everything into setup.cfg, but setup.py still has to be there otherwise `pip install -e .` doesn't work, doesn't really make sense. I'd rather keep the setup.py until there's a proper declarative solution that allows us to remove setup.py. I'm thinking pyproject.toml here. PEP518 and PEP621 are there and it seems that on the long run this fill will replace setup.py and setup.cfg (and maybe requirements.txt) but we're not there yet.

2021-06-27 19:24 UTC, KOLANICH commented
>but setup.py still has to be there otherwise pip install -e . doesn't work

Not quite true, in the latest `pip` it should work because of the patch by me.

>PEP518 and PEP621 are there and it seems that on the long run this fill will replace setup.py and setup.cfg

I guess `setuptools`, which looks stagnating (implementing support of PEP621 (without tests) looks like can take at most 2 days of full time work, but it has not been done yet), can be replaced by competing tools in the most of packages earlier. Anyway, if there is an existing `setup.cfg` where all the metadata resides, it will be much easier to move the metadata from it to `pyproject.toml`: it can be done fully automatically. `setup.cfg` support is present for more than 5 years and we can get the benefits it brings right now, not waiting for the events of indefinitely remote future.

2021-06-28 12:21 UTC, pquentin commented
You can't use the README file directly, because it contains a `raw` directive that works on GitHub but not on PyPI. This is what those lines were about:

https://github.com/urllib3/urllib3/blob/dfd8b580adb4f87388310c11b5c76d989bd6c4e3/setup.py#L47-L60

And this is why the CI currently fails. (And you also have a conflict.)

> Not quite true, in the latest pip it should work because of the patch by me.

I see this was released two months ago. By default Python versions won't come up with this version of pip, and this can be confusing. But this is mostly about contributor experience, not install/use experience, so it may not be a big issue. Anyway, the `raw` issue above is a bigger problem.

2021-06-28 12:25 UTC, pquentin commented
By the way, the latest Python version we support in the `main` branch is Python 3.6, and that is [bundled with pip 9.0.1 and setuptools 28.8.0](https://github.com/python/cpython/commit/756b45ab6e0d8d88f985cf449298145244bd317b), so I'd say anything that pip 9.0.1+ and setuptools 28.8.0+ support is fair game in the `main` branch. (Assuming we keep the Python 2 specific code in setup.py, that is.)

2021-09-17 10:23 UTC, pquentin commented
Since v2 is going to be Python 3.7+, we can assume pip 10 and setuptools 28.8 now: https://github.com/python/cpython/blob/v3.7.0/Lib/ensurepip/__init__.py.

To be clear, I'd be happy with a pull request that moves the declarative parts of setup.py to setup.cfg and switches to python -m build. But let's keep the code that checks for Python 2, that massages the README and that reads the version for now.

2021-09-17 14:00 UTC, sethmlarson commented
There hasn't been any movement on this PR in a few months. We'd still accept what @pquentin mentioned but in it's current state we can't accept this PR. If you'd like to pick up this work @KOLANICH ping us here and we can reopen or you can start a new PR. Thanks again!

2021-09-17 14:00 UTC, closed without merging

2021-09-17 14:06 UTC, bluetech commented
Anyone doing this might be interested in [this tool](https://github.com/asottile/setup-py-upgrade) by asottile which does some of this automatically.

2021-09-19 17:56 UTC, KOLANICH commented
@bluetech, thanks. I used https://github.com/gvalkov/setuptools-py2cfg , but not quite it, but my fork of it with some of the stuff not yet merged into upstream https://github.com/KOLANICH-tools/setuptools-py2cfg/tree/private .

2021-09-19 17:59 UTC, KOLANICH commented
>There hasn't been any movement on this PR in a few months. We'd still accept what @pquentin mentioned but in it's current state we can't accept this PR. If you'd like to pick up this work @KOLANICH ping us here and we can reopen or you can start a new PR. Thanks again!

This PR main purpose is to eliminate `setup.py` completely. If it is not eliminated, it won't bring security benefit.