Explicitly chain or don't chain exceptions
urllib3/urllib3 pull request #2340
Opened 2021-07-25 09:26 UTC by bluetech

Explicitly chain exceptions (or disable the chaining) instead of creating implicit "During handling of the above exception, another exception occurred" which look like a bug.

Since urllib3 is now Python 3 only, we can use the built-in syntax for this.

Methodology: grepped for `raise` and went over each case, deciding whether to chain or `from None`. When in doubt I preferred to chain.

Fixes #2313.

2021-07-27 12:31 UTC, sethmlarson requested changes
Nice! Only have a couple of comments for you then this LGTM:

2021-07-27 12:31 UTC, sethmlarson commented on src/urllib3/contrib/_securetransport/bindings.py
> +    raise ImportError("Error initializing ctypes") from e
This can be `from None`

2021-07-27 12:31 UTC, sethmlarson commented on src/urllib3/contrib/_securetransport/low_level.py
> +        raise ssl.SSLError(f"Unable to allocate array: {e}") from e
This can be `from None`

2021-07-28 16:24 UTC, bluetech commented on src/urllib3/contrib/_securetransport/bindings.py
> +    raise ImportError("Error initializing ctypes") from e
Done! (The other one to)

2021-08-15 18:46 UTC, sethmlarson submitted a review, later dismissed
LGTM, thanks for this!!

2021-08-15 20:43 UTC, merged