[1.26] Deprecate BACKOFF_MAX to introduce DEFAULT_BACKOFF_MAX
urllib3/urllib3 pull request #2495
Opened 2021-11-29 17:03 UTC by pyrooka

This PR is the deprecation part of the following one: https://github.com/urllib3/urllib3/pull/2494

2021-12-08 17:34 UTC, pyrooka commented
I see no issues when I check the codecov report, but it's failing. Any idea what to do?

2021-12-10 03:55 UTC, sethmlarson commented
@pyrooka Don't worry about Codecov, it's really unreliable on the commit status. We can make sure things are okay when we review them.

2021-12-10 03:56 UTC, sethmlarson requested changes
Sorry, I started this review but didn't hit submit. Thanks for this!

2021-12-13 09:38 UTC, pyrooka commented on src/urllib3/util/retry.py
> +            "Using 'Retry.DEFAULT_METHOD_WHITELIST' is deprecated and "
Yeah, that was copy-paste error, fixed!

2021-12-13 09:43 UTC, pyrooka commented on test/test_retry_deprecated.py
> +
How do you mean? Doesn't the `expect_retry_deprecation` fixture enough to test the warning?

2022-01-02 17:19 UTC, sethmlarson approved these changes
Thanks for this!

2022-01-02 21:46 UTC, merged