Check keylog_filename existence
urllib3/urllib3 pull request #2525
Opened 2022-01-08 04:27 UTC by Ghaaf

If the file path doesn't exist it throw following exception:
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))'

2022-01-09 21:09 UTC, sethmlarson requested changes
Thanks for reporting this, however I think raising an error instead of silently doing nothing is the right call for this scenario. What type of error gets raised when you configure a `ca_certs` that doesn't exist? We should try to match that behavior.

We'll also need a test case confirming the behavior.

2022-01-09 22:04 UTC, Ghaaf commented
> Thanks for reporting this, however I think raising an error instead of silently doing nothing is the right call for this scenario. What type of error gets raised when you configure a `ca_certs` that doesn't exist? We should try to match that behavior.
> 
> We'll also need a test case confirming the behavior.

I was stuck with `pip` on my windows machine for a while because the `SSLKEYLOGFILE` points to a non-existing file path on my Windows environment, so I failed to install any package using pip, but this warning all the time. Spending some time to fix the issue, I found the problem on `site-packages\pip\_vendor\urllib3\util\ssl_.py`, changing my environment path to an existing file name, fixed the problem. I'm sure about the change, but unclear which package needs to fix the issue (pip or urllib3).
My test case was `Windows 7`, `Python3.8` with the latest `pip`(`21.3.1` at the moment) contains `urllib3 1.26.7`

2022-01-09 22:21 UTC, sethmlarson commented
@Ghaaf The fix should definitely go in urllib3. Then all users of urllib3, Requests, pip, etc would benefit from its inclusion.

2022-01-17 18:09 UTC, sethmlarson commented
Going to close this for the reasons listed above. If you'd like to land this PR in urllib3 please follow this comment: https://github.com/urllib3/urllib3/pull/2525#pullrequestreview-847304993

2022-01-17 18:09 UTC, closed without merging