Create our own logic for chunking, content framing
urllib3/urllib3 pull request #2565
Opened 2022-02-13 21:04 UTC by sethmlarson

- Changes `HTTPConnection.request_chunked()` into an alias for `HTTPConnection.request(..., chunked=True)`
- Adds a `chunked` parameter to `HTTPConnection.request()`
- Adds a new internal function `body_to_chunks()` which does discovery of Content-Length if applicable for the body/method and converts the body if any into an iterable of `socket.sendall()`-able chunks.
- Changes `HTTPConnection.request()` to use `.putrequest()`, `putheader()`, and `.endheaders()` and to send the body via `.send()` in chunks which was previously handled by `http.client.HTTPConnection`.

All of these changes are necessary for us to one day add another HTTP implementation as we're not relying on `http.client` logic for figuring out content framing, sending of data.

Closes https://github.com/urllib3/urllib3/issues/2515
Closes https://github.com/urllib3/urllib3/issues/2291

2022-02-21 17:20 UTC, pquentin commented
This is exciting! Can you please look into the CI failures?

2022-02-25 21:24 UTC, sethmlarson commented
We may need to work on #2242 before we can land this one now that we're sending headers without `.itermerged()`. Only failing test is:

```
test_headers_http_header_dict failed (1 runs remaining out of 2).
	<class 'AssertionError'>
	assert '1,2' == '1, 2'
  - 1, 2
  ?   -
  + 1,2
	[<TracebackEntry /Users/runner/work/urllib3/urllib3/test/with_dummyserver/test_poolmanager.py:357>]
test_headers_http_header_dict failed; it passed 0 out of the required 1 times.
	<class 'AssertionError'>
	assert '1,2' == '1, 2'
  - 1, 2
  ?   -
  + 1,2
	[<TracebackEntry /Users/runner/work/urllib3/urllib3/test/with_dummyserver/test_poolmanager.py:357>]
```

2022-03-01 06:50 UTC, pquentin commented
I would be happy to just change the test to assert for `1,2` until we land #2242, but I am probably missing something. Also, do you understand the botocore failures?

2022-03-03 04:19 UTC, sethmlarson commented
Discovered that the test was "failing" because we were relying on `tornado.httputil.HTTPHeaders` method of wrapping headers which uses `,` instead of `, `. I've added a new dummyserver handler which keeps the order that headers are received and doesn't fold header values so we can test our header behavior easier.

2022-03-03 04:19 UTC, sethmlarson commented
Also I'm unsure about the botocore failures, going to ping our resident Amazonian @nateprewitt to see if he knows anything about these tests :)

2022-03-03 18:29 UTC, nateprewitt commented
I didn't have a chance to deep dive what specifically is failing but it's definitely around our HTTP 100 functionality. We have some changes injected to handle responses for 100 Continue that are relying on functions in urllib3. It seems we're asserting some of them are called that aren't actually used anymore. I'll see if I can get some time next week to figure out if they're actually legitimate or poorly written tests.

2022-03-06 19:24 UTC, sethmlarson commented
@nateprewitt I'm seeing https://github.com/boto/botocore/blob/8ea47e0ab9f505cc547ac19ce689fd20db3e0241/botocore/awsrequest.py#L109 which appears to add support for `Expect: 100-Continue`, what are your thoughts on upstreaming that logic to urllib3?

2022-03-06 19:30 UTC, nateprewitt commented
We can look at that, but I believe the boto implementation is essentially a hack. It doesn't perform to spec, just enough to be interoperable with s3.

I can look at putting together a test suite from the rfc to validate behavior, but I recall Cory saying it wasn't possible with httplib.

2022-05-02 14:37 UTC, nateprewitt commented
Alrighty, I think this is going to take a while for us to unravel in Botocore. I spoke with Seth this weekend at PyCon and I think the best path forward for now is to skip the failing test in Botocore and we’ll track the fix on our side.

That will get this merged so the prep for 2.0 can move forward and I’ll follow up when it’s safe to remove.

2022-05-02 19:31 UTC, nateprewitt approved these changes

2022-05-03 06:02 UTC, pquentin requested changes
Thanks! I think we're nearly there.

2022-06-01 00:05 UTC, sethmlarson commented on test/with_dummyserver/test_poolmanager.py
> +            assert returned_headers[-4:] == [
We're using a list here to maintain order, I can add a comment about this so we don't lose the coverage there.

2022-06-01 00:14 UTC, sethmlarson commented on changelog/2515.feature.rst
> +Changed ``urllib3.connection.HTTPConnection.request()`` to use ``http.client.HTTPConnection.putrequest()``, ``putheader()``, ``.endheaders()``, and ``.send()`` methods directly.
Sounds good to me! Thanks for calling out implementation details leaking into changelogs.

2022-06-04 19:07 UTC, pquentin commented
This now looks good, but the Windows failures are very mysterious but seem related to the change.

2022-06-17 15:56 UTC, sethmlarson commented
@pquentin I've removed the wrapping of `request_chunked` in our HTTPConnection marker class. Not sure if this fixed the Windows issue we were seeing but things are passing now? Either way we don't want to wrap `request_chunked` there to avoid double sending of the marker.

2022-06-19 07:24 UTC, pquentin approved these changes
LGTM! Thanks for iterating.

2022-06-19 12:29 UTC, merged