Add docs on getting paid for contributions
urllib3/urllib3 pull request #2618
Opened 2022-06-01 01:30 UTC by sethmlarson

:tada: Let's pay some open source contributors! I've created a list of guidelines, let me know what you think.

I can't decide if we want to predetermine amounts we're going to pay for issues being completed or whether we should move to labeling issues as "Paid $$$" without the amounts and then ask contributors to calculate the time spent themselves?

2022-06-01 02:15 UTC, nateprewitt approved these changes
Two minor comments, otherwise looks good :shipit:

2022-06-01 02:15 UTC, nateprewitt commented on docs/contributing.rst
> +- Ensure that you're able to receive funds from OpenCollective.
Does OpenCollective have any information about eligibility or setup we could link to?

2022-06-01 05:47 UTC, pquentin requested changes
Thank you for putting this out there! I like that we recommend $50 per hour.

2022-06-01 15:19 UTC, shazow commented on docs/contributing.rst
> +that is marked with the `"Paid $$$" label <https://github.com/urllib3/urllib3/issues?q=is%3Aissue+is%3Aopen+label%3A%22Paid%20%24%24%24%22>`_ then you're eligible to be paid for your work.
Also the current link in the PR results in 0 matches.

2022-06-02 03:36 UTC, sethmlarson commented
Okay I've fixed "Open Collective", linked to another part of their FAQ for eligibility, mentioned contract/tax restrictions being a thing. Most important change is switching to a "predetermined amount" for work (what we "have" setup currently).

If we go this way I'd like to boost the amounts for current issues. Should we go with small/medium/large and $100/$300/$500, I'm guessing some of our $300 issues will likely take longer than 6 hours.

2022-06-02 14:12 UTC, shazow approved these changes

2022-06-02 14:20 UTC, nateprewitt approved these changes

2022-06-02 18:40 UTC, pquentin approved these changes

2022-06-02 18:41 UTC, merged