Added deprecation warning for urllib3.contrib.securetransport
urllib3/urllib3 pull request #2695
Opened 2022-07-31 08:18 UTC by IvanLauLinTiong

This PR is to address issue #2692

2022-07-31 20:06 UTC, sethmlarson requested changes
Few comments:

- Let's point people to this issue: https://github.com/urllib3/urllib3/issues/2681 in both the documentation and the warning message. That way we can provide updates if necessary on the situation.

Also note I rejected your Open Collective expense as the work hadn't been completed yet, hold off on creating one until the work is complete. Thanks!

2022-07-31 20:06 UTC, sethmlarson commented on src/urllib3/contrib/securetransport.py
> +    "'securetransport' module is deprecated and will be removed "
Let's use the full name of the module: `urllib3.contrib.securetransport`.

2022-07-31 20:06 UTC, sethmlarson commented on src/urllib3/contrib/securetransport.py
> +    DeprecationWarning,
Let's use the `category=DeprecationWarning` keyword argument here.

2022-07-31 20:06 UTC, sethmlarson commented on src/urllib3/contrib/securetransport.py
> +    "in a future release of urllib3 2.x. Read more in doc: "
"Read more in this issue: ..."

2022-08-01 16:19 UTC, IvanLauLinTiong commented
Hi @sethmlarson ,  I have addressed all your comments in latest commit.

2022-08-04 13:35 UTC, sethmlarson approved these changes
LGTM. Thanks for this!

2022-08-04 13:36 UTC, merged