Change dependency warning link for PySocks
urllib3/urllib3 pull request #2964
Opened 2023-04-15 09:54 UTC by dslackw

2023-04-15 13:38 UTC, pquentin commented
Thanks! Did you mean to raise this against the 1.26 branch?

2023-04-16 06:29 UTC, dslackw commented
Yes, if you think is the right branch.

2023-04-17 07:50 UTC, pquentin requested changes
I had missed that you change

2023-04-17 07:50 UTC, pquentin commented on src/urllib3/contrib/socks.py
> +            "https://urllib3.readthedocs.io/en/stable/advanced-usage.html#socks-proxies"
I had missed from my phone that contrib was changed to advanced-usage, sorry. But this is the main branch, so we should stick with `latest` please:

```suggestion
            "https://urllib3.readthedocs.io/en/latest/advanced-usage.html#socks-proxies"
```

2023-06-27 03:40 UTC, sethmlarson approved these changes
LGTM, thank you!

2023-11-23 21:55 UTC, illia-v approved these changes

2023-11-23 21:55 UTC, merged