Disable tunnel for http2 requests
urllib3/urllib3 pull request #3321
Opened 2024-01-25 20:01 UTC by Nightrider0098

2024-01-26 12:01 UTC, pquentin reviewed
Thanks, can you please add an unit test to make sure this isn't lost in a later refactoring?

Also, please make sure to add "Closes #XXXX" in your pull request description. This closes the issue automatically when the pull request is merged, and helps understanding what you're fixing. I've just edited your pull request to include that.

2024-01-26 14:32 UTC, sethmlarson commented
I'm also imagining a test case that checks the bytes sent over the socket for the absence of the "h2" ALPN in the TLS ClientHello, I believe we do something similar for server name?

2024-01-29 11:46 UTC, pquentin commented
> I'm also imagining a test case that checks the bytes sent over the socket for the absence of the "h2" ALPN in the TLS ClientHello, I believe we do something similar for server name?

I did not know, but we do have a SNI socketlevel test: `test_hostname_in_first_request_packet`. And we even have an ALPN test: https://github.com/urllib3/urllib3/blob/d7bb83b48c23d8dd429c20a43ac3da74ea6e9df0/test/with_dummyserver/test_socketlevel.py#L108-L133

We will eventually have to adapt this to test to include checking that the `h2` ALPN is included for normal requests, but that can happen in another PR. I also tried checking what happens when setting up a tunnel in a modified version of this test, but I realized that this pull request makes sure the request does not even go out (raises `NotImplementedError`).

And since the request does not go out, it does not have to be a test that includes a server in `test_with_dummyserver/test_proxy_poolmanager.py`. It can be in `test/test_proxymanager.py`. When using the `http_version` fixture and `http_version` is equal to `http2`, doing a [tunnel request (with HTTP CONNECT)](https://urllib3.readthedocs.io/en/stable/advanced-usage.html#proxies) should raise `NotImplementedError`.

2024-01-29 14:18 UTC, sigmavirus24 requested changes

2024-01-29 14:18 UTC, sigmavirus24 commented on .gitignore
> +venv/
I'd prefer we not add things here. You should use a global gitignore if there's a way you're working that is different from the project conventions

2024-02-08 02:42 UTC, Nightrider0098 commented
@pquentin Should i override set_tunnel in connection pool or writing the check in __init__ is fine?

2024-02-08 05:57 UTC, sethmlarson reviewed
Thank you for this PR, I have a suggestion that'll ensure the test case is useful into the near future where `HTTPSConnection` begins speaking HTTP/2 on its own (without a separate connection).

The approach would be:

* Setup a socket server that records the handshake bytes
* Send a tunnel proxy connection with TLS handshake
* Assert that the bytes for an ALPN of `http/1.1` are there, but not `h2`.

This way in the future when the two connections are combined together this test case is still useful and it removes the need for the other tests.

2024-02-08 05:59 UTC, sethmlarson commented
See this test which verifies that the hostname is in the initial TLS handshake via SNI: https://github.com/urllib3/urllib3/blob/main/test/with_dummyserver/test_socketlevel.py#L103

Can assert the `http/1.1` and `h2` ALPN strings in a similar way.

2024-02-08 13:15 UTC, pquentin commented
Thanks! Can you please look into the CI failures?

2024-02-08 13:48 UTC, sethmlarson requested changes

2024-02-08 13:48 UTC, sethmlarson commented on test/with_dummyserver/test_socketlevel.py
> +        base_url = f"http://{self.host}:{self.port}"
This is using HTTPS, tunneling and ALPN are TLS features so requires HTTPS. It's expected for the handshake to fail, we want to see what ALPN values are being offered and not complete the handshake.

2024-02-08 13:48 UTC, sethmlarson commented on test/with_dummyserver/test_socketlevel.py
> +            assert b"HTTP/1.1" in self.buf
For ALPN the value is `b"http/1.1"`.

2024-08-13 18:36 UTC, pquentin commented
> Thank you for this PR, I have a suggestion that'll ensure the test case is useful into the near future where `HTTPSConnection` begins speaking HTTP/2 on its own (without a separate connection). [...]

I'm confused by this message. Are you suggesting that enabling HTTP CONNECT to an otherwise HTTP/2 capable host should downgrade to HTTP/1.1? I also don't understand what "speaking HTTP/2 on its own" and "without a separate connection" mean. I think laying out what should happen now and later and how this test will cover both cases would help me a lot.

2024-08-13 19:00 UTC, sethmlarson commented
@pquentin Sorry that comment is indeed a bit confusing!

> `HTTPSConnection` begins speaking HTTP/2 on its own (without a separate connection). [...]

This was meant to mean when `urllib3.connection.HTTPSConnection` automatically uses HTTP/2, instead of through `urllib3.http2.connection.HTTP2Connection`.

2024-08-15 17:02 UTC, pquentin commented on test/with_dummyserver/test_connectionpool.py
> -        # note the actual httplib.py has no tests for this functionality
This has been tested for 10 years now! 5 years after urllib3's first commit. https://github.com/python/cpython/blob/e001027188001f4bdf6ea16f70726ca0fabe85c4/Lib/test/test_httplib.py#L2225

2024-08-15 18:14 UTC, sethmlarson approved these changes
Thanks Quentin!

2024-08-15 18:29 UTC, merged

2024-08-15 18:30 UTC, pquentin commented
@Nightrider0098 Thanks for your help here! While I brought this to the finish line, the $100 bounty associated to this issue is yours and you can claim it on OpenCollective.